personajes = {
    "Susan": {"nombre": "Susan", "características": ["Pelo", "Ojos Marrones", "Coloretes", "Mujer", "Pelo Blanco"]},
    "Claire": {"nombre": "Claire", "características": ["Pelo", "Sombrero", "Ojos Marrones", "Gafas", "Mujer", "Pelo Naranja"]},
    "David": {"nombre": "David", "características": ["Pelo", "Ojos Marrones", "Barba", "Hombre", "Rubio"]},
    "Anne": {"nombre": "Anne", "características": ["Pelo", "Ojos Marrones", "Pendientes", "Mujer", "Pelo Marrón"]},
    "Robert": {"nombre": "Robert", "características": ["Pelo", "Ojos Azules", "Coloretes", "Hombre", "Pelo Marrón"]},
    "Anita": {"nombre": "Anita", "características": ["Pelo", "Ojos Azules", "Coloretes", "Mujer", "Rubio"]},
    "Joe": {"nombre": "Joe", "características": ["Pelo", "Ojos Marrones", "Gafas", "Hombre", "Rubio"]},
    "George": {"nombre": "George", "características": ["Pelo", "Sombrero", "Ojos Marrones", "Hombre", "Pelo Blanco"]},
    "Bill": {"nombre": "Bill","características": ["Calvo", "Ojos Marrones", "Coloretes", "Barba", "Hombre"]},
    "Alfred": {"nombre": "Alfred", "características": ["Pelo", "Ojos Azules", "Bigote", "Hombre", "Pelo Naranja"]},
    "Max": {"nombre": "Max", "características": ["Pelo", "Ojos Marrones", "Bigote", "Hombre", "Pelo Marrón"]},
    "Tom": {"nombre": "Tom", "características": ["Calvo", "Ojos Azules", "Gafas", "Hombre"]},
    "Alex": {"nombre": "Alex", "características": ["Pelo", "Ojos Marrones", "Bigote", "Hombre", "Pelo Marrón"]},
    "Sam": {"nombre": "Sam", "características": ["Calvo", "Ojos Marrones", "Gafas", "Hombre"]},
    "Richard": {"nombre": "Richard", "características": ["Calvo", "Ojos Marrones", "Bigote", "Barba", "Hombre"]},
    "Paul": {"nombre": "Paul", "características": ["Pelo", "Ojos Marrones", "Gafas", "Hombre", "Pelo Blanco"]},
    "Maria": {"nombre": "Maria", "características": ["Pelo", "Sombrero", "Ojos Marrones", "Pendientes", "Mujer", "Pelo Marrón"]},
    "Frans": {"nombre": "Frans", "características": ["Pelo", "Ojos Marrones", "Hombre", "Pelo Naranja"]},
    "Herman": {"nombre": "Herman", "características": ["Calvo", "Ojos Marrones", "Hombre"]},
    "Bernard": {"nombre": "Bernard", "características": ["Pelo", "Sombrero", "Ojos Marrones", "Hombre", "Pelo Marrón"]},
    "Philip": {"nombre": "Philip", "características": ["Pelo", "Ojos Marrones", "Coloretes", "Barba", "Hombre", "Pelo Marrón"]},
    "Eric": {"nombre": "Eric", "características": ["Pelo", "Sombrero", "Ojos Marrones", "Hombre", "Pelo Rubio"]},
    "Charles": {"nombre": "Charles", "características": ["Pelo", "Ojos Marrones", "Bigote", "Hombre", "Rubio"]},
    "Peter": {"nombre": "Peter", "características": ["Pelo", "Ojos Azules", "Hombre", "Pelo Blanco"]},
}
