personajes = {
    "Susan": {"nombre": "Susan", "características": [Pelo, Ojos Marrones,]},
    "Claire": {"nombre": "Claire", "características": [Pelo, Sombrero, Ojos Marrones, Gafas]},
    "David": {"nombre": "David", "características": [Pelo, Ojos Marrones ]},
    "Anne": {"nombre": "Anne", "características": [Pelo, Ojos Marrones ]},
    "Robert": {"nombre": "Robert", "características": [Pelo, Ojos Azules ]},
    "Anita": {"nombre": "Anita", "características": [Pelo, Ojos Azules ]},
    "Joe": {"nombre": "Joe", "características": [Pelo, Ojos Marrones, Gafas  ]},
    "George": {"nombre": "George", "características": [Pelo, Sombrero, Ojos Marrones  ]},
    "Bill": {"nombre": "Bill", "características": [Calvo, Ojos Marrones ]},
    "Alfred": {"nombre": "Alfred", "características": [Pelo, Ojos Azules]},
    "Max": {"nombre": "Max", "características": [Pelo, Ojos Marrones ]},
    "Tom": {"nombre": "Tom", "características": [Calvo, Ojos Azules, Gafas ]},
    "Alex": {"nombre": "Alex", "características": [Pelo, Ojos Marrones ]},
    "Sam": {"nombre": "Sam", "características": [Calvo, Ojos Marrones, Gafas]},
    "Richard": {"nombre": "Richard", "características": [Calvo, Ojos Marrones ]},
    "Paul": {"nombre": "Paul", "características": [Pelo, Ojos Marrones, Gafas ]},
    "Maria": {"nombre": "Maria", "características": [Pelo, Sombrero, Ojos Marrones]},
    "Frans": {"nombre": "Frans", "características": [Pelo, Ojos Marrones ]},
    "Herman": {"nombre": "Herman", "características": [Calvo, Ojos Marrones ]},
    "Bernard": {"nombre": "Bernard", "características": [Pelo, Sombrero, Ojos Marrones ]},
    "Philip": {"nombre": "Philip", "características": [Pelo, Ojos Marrones ]},
    "Eric": {"nombre": "Eric", "características": [Pelo, Sombrero, Ojos Marrones  ]},
    "Charles": {"nombre": "Charles", "características": [Pelo, Ojos Marrones ]},
    "Peter": {"nombre": "Peter", "características": [Pelo, Ojos Azules, ]},
}